# Generated by Django 3.1 on 2020-09-30 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200930_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fullname',
            new_name='name',
        ),
    ]
