# Generated by Django 3.1 on 2020-10-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='statement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
