# Generated by Django 3.1 on 2020-10-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Adress',
            new_name='Address',
        ),
    ]
