# Generated by Django 3.1 on 2020-10-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20201001_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='address',
        ),
    ]
