# Generated by Django 3.1 on 2020-10-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20201001_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='finish',
            field=models.CharField(help_text='when you open your office', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='start',
            field=models.CharField(help_text='when you open your office', max_length=100, null=True),
        ),
    ]
