# Generated by Django 3.1 on 2020-10-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20201002_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='address',
            name='start',
        ),
        migrations.AddField(
            model_name='address',
            name='worktime',
            field=models.CharField(help_text='office time', max_length=100, null=True),
        ),
    ]
