# Generated by Django 3.1 on 2020-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20201002_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='worktime',
            field=models.CharField(help_text='office time Mon-Fri 09:00-17:00', max_length=100, null=True),
        ),
    ]
