# Generated by Django 3.1 on 2020-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_heading',
            name='title',
        ),
        migrations.AddField(
            model_name='service_heading',
            name='title_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_heading',
            name='title_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
