# Generated by Django 3.1 on 2020-09-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200929_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_heading',
            options={'ordering': ['date_posted'], 'verbose_name': 'Heading', 'verbose_name_plural': 'Heading'},
        ),
        migrations.RemoveField(
            model_name='service_heading',
            name='slug',
        ),
    ]
