# Generated by Django 3.1 on 2020-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200929_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='Service/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons/%Y/%m/%d/'),
        ),
    ]
