# Generated by Django 3.1 on 2020-09-30 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='title',
            new_name='title_1',
        ),
        migrations.AddField(
            model_name='solution',
            name='title_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
