# Generated by Django 3.1 on 2020-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20200930_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='fact_count_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_count_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_count_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_count_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_title_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_title_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_title_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_title_4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
