# Generated by Django 3.1 on 2020-09-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20200930_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='slug',
        ),
    ]
