# Generated by Django 3.1 on 2020-09-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_solution_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='fact_count_1',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_count_2',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_count_3',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_count_4',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_title_1',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_title_2',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_title_3',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_title_4',
        ),
        migrations.AddField(
            model_name='solution',
            name='count_1',
            field=models.CharField(help_text='facts in number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='count_2',
            field=models.CharField(help_text='facts in number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='count_3',
            field=models.CharField(help_text='facts in number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='count_4',
            field=models.CharField(help_text='facts in number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_1',
            field=models.CharField(help_text='facts about your business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_2',
            field=models.CharField(help_text='facts about your business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_3',
            field=models.CharField(help_text='facts about your business', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='fact_4',
            field=models.CharField(help_text='facts about your business', max_length=200, null=True),
        ),
    ]
