# Generated by Django 3.1 on 2020-09-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20200930_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='image',
            field=models.ImageField(null=True, upload_to='Solutions/%Y/%m/%d/'),
        ),
    ]
