# Generated by Django 3.1 on 2020-09-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_solution_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='slug',
            field=models.SlugField(default='business-solution', max_length=200, null=True, unique=True),
        ),
    ]
