# Generated by Django 3.1 on 2020-09-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20200930_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='count_1',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='count_2',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='count_3',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='count_4',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_1',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_2',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_3',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='fact_4',
        ),
    ]
