# Generated by Django 3.1 on 2020-09-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20200930_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='title_1',
            new_name='title_section_1',
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='title_2',
            new_name='title_section_2',
        ),
    ]
