# Generated by Django 3.1 on 2020-09-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20200930_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='title_section_1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='title_section_2',
        ),
    ]
