# Generated by Django 3.1 on 2020-09-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20200930_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_heading',
            old_name='title_1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service_heading',
            name='title_2',
        ),
    ]
