# Generated by Django 3.1 on 2020-09-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
