# Generated by Django 3.1 on 2020-09-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slide_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='photo',
            new_name='image',
        ),
    ]
