# Generated by Django 3.1 on 2020-10-01 10:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200928_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='footer_pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='about', max_length=200, null=True, unique=True)),
                ('statement', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='About/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.footer')),
            ],
        ),
    ]
