# Generated by Django 3.1 on 2020-10-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footer_footer_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='footer_pages',
            new_name='footer_page',
        ),
    ]
