# Generated by Django 3.1 on 2020-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201001_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer_page',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
