# Generated by Django 3.1 on 2020-10-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201001_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer_page',
            old_name='footer',
            new_name='category',
        ),
    ]
