# Generated by Django 3.1 on 2020-10-01 13:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201001_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('statement', models.CharField(max_length=400)),
                ('thumbnail', models.ImageField(null=True, upload_to='Pages/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.footer')),
            ],
        ),
        migrations.DeleteModel(
            name='footer_page',
        ),
    ]
