# Generated by Django 3.1 on 2020-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201001_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_footer_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_footer_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_footer_3',
            field=models.BooleanField(default=False),
        ),
    ]
