# Generated by Django 3.1 on 2020-09-30 10:43

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_section_1', models.CharField(max_length=200)),
                ('title_Section_2', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='about', max_length=200, null=True, unique=True)),
                ('statement', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='Solutions/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
