# Generated by Django 3.1 on 2020-09-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='title_Section_2',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_section_1',
        ),
    ]
