# Generated by Django 3.1 on 2020-09-30 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200930_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='about', max_length=200, null=True, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(null=True, upload_to='Solutions/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mvp', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['date_posted'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
    ]
