# Generated by Django 3.1 on 2020-09-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200930_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['date_posted'], 'verbose_name': 'Team', 'verbose_name_plural': 'Lapset Ajibika Team'},
        ),
        migrations.AddField(
            model_name='team',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
